services:
  nest-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: store-app
    ports:
      - '3300:3000'
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm run start
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:17.2-alpine
    container_name: store-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d store_db']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
