services:
  nest-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: store-app
    ports:
      - '3300:3000'
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:root@postgres-db:5432/store_db

  postgres-db:
    image: postgres:17.2-alpine
    container_name: store-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: store_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d store_db']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
